package com.exampl.communt.mapper;

import com.exampl.communt.mode.PublishMode;
import com.exampl.communt.mode.PublishModeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface PublishModeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publish
     *
     * @mbg.generated Wed Oct 16 13:29:26 CST 2019
     */
    long countByExample(PublishModeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publish
     *
     * @mbg.generated Wed Oct 16 13:29:26 CST 2019
     */
    int deleteByExample(PublishModeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publish
     *
     * @mbg.generated Wed Oct 16 13:29:26 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publish
     *
     * @mbg.generated Wed Oct 16 13:29:26 CST 2019
     */
    int insert(PublishMode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publish
     *
     * @mbg.generated Wed Oct 16 13:29:26 CST 2019
     */
    int insertSelective(PublishMode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publish
     *
     * @mbg.generated Wed Oct 16 13:29:26 CST 2019
     */
    List<PublishMode> selectByExampleWithRowbounds(PublishModeExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publish
     *
     * @mbg.generated Wed Oct 16 13:29:26 CST 2019
     */
    List<PublishMode> selectByExample(PublishModeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publish
     *
     * @mbg.generated Wed Oct 16 13:29:26 CST 2019
     */
    PublishMode selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publish
     *
     * @mbg.generated Wed Oct 16 13:29:26 CST 2019
     */
    int updateByExampleSelective(@Param("record") PublishMode record, @Param("example") PublishModeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publish
     *
     * @mbg.generated Wed Oct 16 13:29:26 CST 2019
     */
    int updateByExample(@Param("record") PublishMode record, @Param("example") PublishModeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publish
     *
     * @mbg.generated Wed Oct 16 13:29:26 CST 2019
     */
    int updateByPrimaryKeySelective(PublishMode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publish
     *
     * @mbg.generated Wed Oct 16 13:29:26 CST 2019
     */
    int updateByPrimaryKey(PublishMode record);
}