package com.exampl.communt.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PublishMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publish
     *
     * @mbg.generated Wed Oct 09 16:16:01 CST 2019
     */
    long countByExample(PublishExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publish
     *
     * @mbg.generated Wed Oct 09 16:16:01 CST 2019
     */
    int deleteByExample(PublishExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publish
     *
     * @mbg.generated Wed Oct 09 16:16:01 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publish
     *
     * @mbg.generated Wed Oct 09 16:16:01 CST 2019
     */
    int insert(Publish record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publish
     *
     * @mbg.generated Wed Oct 09 16:16:01 CST 2019
     */
    int insertSelective(Publish record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publish
     *
     * @mbg.generated Wed Oct 09 16:16:01 CST 2019
     */
    List<Publish> selectByExample(PublishExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publish
     *
     * @mbg.generated Wed Oct 09 16:16:01 CST 2019
     */
    Publish selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publish
     *
     * @mbg.generated Wed Oct 09 16:16:01 CST 2019
     */
    int updateByExampleSelective(@Param("record") Publish record, @Param("example") PublishExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publish
     *
     * @mbg.generated Wed Oct 09 16:16:01 CST 2019
     */
    int updateByExample(@Param("record") Publish record, @Param("example") PublishExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publish
     *
     * @mbg.generated Wed Oct 09 16:16:01 CST 2019
     */
    int updateByPrimaryKeySelective(Publish record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publish
     *
     * @mbg.generated Wed Oct 09 16:16:01 CST 2019
     */
    int updateByPrimaryKey(Publish record);
}