package com.exampl.communt.mode;

public class PublishMode {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column publish.id
     *
     * @mbg.generated Wed Oct 09 17:32:41 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column publish.title
     *
     * @mbg.generated Wed Oct 09 17:32:41 CST 2019
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column publish.describe_text
     *
     * @mbg.generated Wed Oct 09 17:32:41 CST 2019
     */
    private String describeText;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column publish.label
     *
     * @mbg.generated Wed Oct 09 17:32:41 CST 2019
     */
    private String label;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column publish.creat_id
     *
     * @mbg.generated Wed Oct 09 17:32:41 CST 2019
     */
    private String creatId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column publish.reply_count
     *
     * @mbg.generated Wed Oct 09 17:32:41 CST 2019
     */
    private Integer replyCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column publish.view_count
     *
     * @mbg.generated Wed Oct 09 17:32:41 CST 2019
     */
    private Integer viewCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column publish.gmt_create
     *
     * @mbg.generated Wed Oct 09 17:32:41 CST 2019
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column publish.gmt_modified
     *
     * @mbg.generated Wed Oct 09 17:32:41 CST 2019
     */
    private Long gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column publish.id
     *
     * @return the value of publish.id
     *
     * @mbg.generated Wed Oct 09 17:32:41 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column publish.id
     *
     * @param id the value for publish.id
     *
     * @mbg.generated Wed Oct 09 17:32:41 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column publish.title
     *
     * @return the value of publish.title
     *
     * @mbg.generated Wed Oct 09 17:32:41 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column publish.title
     *
     * @param title the value for publish.title
     *
     * @mbg.generated Wed Oct 09 17:32:41 CST 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column publish.describe_text
     *
     * @return the value of publish.describe_text
     *
     * @mbg.generated Wed Oct 09 17:32:41 CST 2019
     */
    public String getDescribeText() {
        return describeText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column publish.describe_text
     *
     * @param describeText the value for publish.describe_text
     *
     * @mbg.generated Wed Oct 09 17:32:41 CST 2019
     */
    public void setDescribeText(String describeText) {
        this.describeText = describeText == null ? null : describeText.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column publish.label
     *
     * @return the value of publish.label
     *
     * @mbg.generated Wed Oct 09 17:32:41 CST 2019
     */
    public String getLabel() {
        return label;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column publish.label
     *
     * @param label the value for publish.label
     *
     * @mbg.generated Wed Oct 09 17:32:41 CST 2019
     */
    public void setLabel(String label) {
        this.label = label == null ? null : label.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column publish.creat_id
     *
     * @return the value of publish.creat_id
     *
     * @mbg.generated Wed Oct 09 17:32:41 CST 2019
     */
    public String getCreatId() {
        return creatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column publish.creat_id
     *
     * @param creatId the value for publish.creat_id
     *
     * @mbg.generated Wed Oct 09 17:32:41 CST 2019
     */
    public void setCreatId(String creatId) {
        this.creatId = creatId == null ? null : creatId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column publish.reply_count
     *
     * @return the value of publish.reply_count
     *
     * @mbg.generated Wed Oct 09 17:32:41 CST 2019
     */
    public Integer getReplyCount() {
        return replyCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column publish.reply_count
     *
     * @param replyCount the value for publish.reply_count
     *
     * @mbg.generated Wed Oct 09 17:32:41 CST 2019
     */
    public void setReplyCount(Integer replyCount) {
        this.replyCount = replyCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column publish.view_count
     *
     * @return the value of publish.view_count
     *
     * @mbg.generated Wed Oct 09 17:32:41 CST 2019
     */
    public Integer getViewCount() {
        return viewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column publish.view_count
     *
     * @param viewCount the value for publish.view_count
     *
     * @mbg.generated Wed Oct 09 17:32:41 CST 2019
     */
    public void setViewCount(Integer viewCount) {
        this.viewCount = viewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column publish.gmt_create
     *
     * @return the value of publish.gmt_create
     *
     * @mbg.generated Wed Oct 09 17:32:41 CST 2019
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column publish.gmt_create
     *
     * @param gmtCreate the value for publish.gmt_create
     *
     * @mbg.generated Wed Oct 09 17:32:41 CST 2019
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column publish.gmt_modified
     *
     * @return the value of publish.gmt_modified
     *
     * @mbg.generated Wed Oct 09 17:32:41 CST 2019
     */
    public Long getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column publish.gmt_modified
     *
     * @param gmtModified the value for publish.gmt_modified
     *
     * @mbg.generated Wed Oct 09 17:32:41 CST 2019
     */
    public void setGmtModified(Long gmtModified) {
        this.gmtModified = gmtModified;
    }
}